DjangoBasico/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

from apps.Tarjeta.views import TarjetaList as tarjeta_view

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', tarjeta_view.as_view(), name="home"),
    url(r'^autor/', include('apps.Autor.urls', namespace="autor")),
    url(r'^tarjeta/', include('apps.Tarjeta.urls', namespace="tarjeta")),
    url(r'^login/$', auth_views.login, {'template_name': 'Auth/login.html'}, name='login'),
    url(r'^logout/$', auth_views.logout, {'next_page': '/'}, name='logout'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/Autor/urls.py
from django.conf.urls import url

from apps.Autor import views

## r'^ruta$', r'^ruta/$'
## (?P<nombre>\w+) string, (?P<nombre>\d+) integer

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^nuevo$', views.create, name='crear'),
    url(r'^(?P<autorid>\d+)/actualizar/$', views.update, name='actualizar'),
    url(r'^(?P<autorid>\d+)/eliminar/$', views.delete, name='eliminar'),
]

apps/Tarjeta/urls.py
from django.conf.urls import url

from apps.Tarjeta import views

## r'^ruta$', r'^ruta/$'
## (?P<nombre>\w+) string, (?P<nombre>\d+) integer

urlpatterns = [
    url(r'^$', views.TarjetaList.as_view(), name='index'),
    url(r'^nuevo$', views.TarjetaCreate.as_view(), name='crear'),
]

apps/Autor/models.py
from django.db import models

# Create your models here.

class Autor(models.Model):
    nombre = models.CharField(max_length=50)
    apellido = models.CharField(max_length=50)
    usuario = models.CharField(max_length=50)

    def __str__(self):
        return '{}'.format(self.usuario)

apps/Tarjeta/models.py
from django.db import models

from apps.Autor.models import Autor

# Create your models here.

class Tarjeta(models.Model):
    titulo = models.CharField(max_length=150)
    contenido = models.TextField(max_length=300)
    imagen = models.ImageField(upload_to='media/')
    autor = models.ForeignKey(Autor, blank=True, null=True, on_delete=models.CASCADE)

apps/Autor/forms.py
from django import forms

from apps.Autor.models import Autor

class AutorForm(forms.ModelForm):
    class Meta:
        model = Autor
        fields = ['apellido', 'nombre', 'usuario']
        widgets = {
            'apellido': forms.TextInput(attrs={'class': 'form-control'}),
            'nombre': forms.TextInput(attrs={'class': 'form-control'}),
            'usuario': forms.TextInput(attrs={'class': 'form-control'}),
        }

apps/Tarjeta/forms.py
from django import forms

from apps.Tarjeta.models import Tarjeta

class TarjetaForm(forms.ModelForm):
    class Meta:
        model = Tarjeta
        fields = ['titulo', 'contenido', 'imagen', 'autor']
        widgets = {
            'titulo': forms.TextInput(attrs={'class': 'form-control'}),
            'contenido': forms.Textarea(attrs={'class': 'form-control'}),
            'autor': forms.Select(attrs={'class': 'form-control'}),
        }

apps/Autor/views.py
from django.shortcuts import render, redirect, get_object_or_404

from apps.Autor.models import Autor
from apps.Autor.forms import AutorForm
from django.contrib import messages
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

# Create your views here.

def index(request):
    autores_list = Autor.objects.all()
    page = request.GET.get('page', 1)
    
    paginator = Paginator(autores_list, 1)
    try:
        autores = paginator.page(page)
    except PageNotAnInteger:
        autores = paginator.page(1)
    except EmptyPage:
        autores = paginator.page(paginator.num_pages)
    
    return render(request, 'Autor/index.html', {'autores': autores, 'messages': messages.get_messages(request)})

def create(request):
    form = AutorForm(request.POST or None)
    if form.is_valid():
        form.save()
        messages.add_message(request, messages.SUCCESS, 'Autor Creado')
        return redirect('autor:index')
    return render(request, 'autor/form.html', {'form': form})

def update(request, autorid):
    autor = get_object_or_404(Autor, id=autorid)
    form = AutorForm(request.POST or None, instance=autor)
    if form.is_valid():
        form.save()
        messages.add_message(request, messages.SUCCESS, 'Autor Actualizado')
        return redirect('autor:index')
    return render(request, 'autor/form.html', {'form': form})

def delete(request, autorid):
    autor = get_object_or_404(Autor, id=autorid)
    autor.delete()
    messages.add_message(request, messages.SUCCESS, 'Autor Eliminado')
    return redirect('autor:index')

apps/Tarjeta/views.py
from django.views.generic import ListView, CreateView
from django.core.urlresolvers import reverse_lazy

from apps.Tarjeta.models import Tarjeta
from apps.Tarjeta.forms import TarjetaForm

# Create your views here.

class TarjetaCreate(CreateView):
    model = Tarjeta
    form_class = TarjetaForm
    template_name = 'tarjeta/form.html'
    success_url = reverse_lazy('tarjeta:index')

class TarjetaList(ListView):
    model = Tarjeta
    template_name = 'tarjeta/index.html'

templates/Autor/form.html
{% extends "layouts/master.html" %}

{% block content %}
    <div class="row">
        <div class="col-sm-8 col-md-6 col-sm-offset-2 col-md-offset-3">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">Formulario de Autores</h3>
                </div>
                <div class="panel-body">
                    <form method="POST" class="form">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <input type="submit" class="btn btn-block btn-primary" value="Guardar">
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/Autor/index.html
{% extends "layouts/master.html" %}

{% block content %}
    <div class="table-autors">
        {% if autores %}
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th>Id</th>
                        <th>Apellido</th>
                        <th>Nombre</th>
                        <th>Usuario</th>
                        <th>Operación</th>
                    </tr>
                </thead>
                <tbody>
                    {% for item in autores %}
                        <tr>
                            <td>{{ item.id }}</td>
                            <td>{{ item.apellido }}</td>
                            <td>{{ item.nombre }}</td>
                            <td>{{ item.usuario }}</td>
                            <td>
                                <div class="btn-group">
                                    <button type="button" class="btn btn-info dropdown-toggle" data-toggle="dropdown">
                                        Seleccione <span class="caret"></span>
                                    </button>
                                    <ul class="dropdown-menu">
                                        <li><a href="{% url 'autor:actualizar' item.id %}">Actualizar</a></li>
                                        <li><a href="{% url 'autor:eliminar' item.id %}">Eliminar</a></li>
                                    </ul>
                                </div>
                            </td>
                        </tr>                    
                    {% endfor %}
                </tbody>
            </table>

            {% if autores.has_other_pages %}
                <ul class="pagination">
                    {% if autores.has_previous %}
                        <li><a href="?page={{ autores.previous_page_number }}">&laquo;</a></li>
                    {% else %}
                        <li class="disabled"><span>&laquo;</span></li>
                    {% endif %}
                    
                    {% for i in autores.paginator.page_range %}
                        {% if autores.number == i %}
                            <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
                        {% else %}
                            <li><a href="?page={{ i }}">{{ i }}</a></li>
                        {% endif %}
                    {% endfor %}
                    
                    {% if autores.has_next %}
                        <li><a href="?page={{ autores.next_page_number }}">&raquo;</a></li>
                    {% else %}
                        <li class="disabled"><span>&raquo;</span></li>
                    {% endif %}
                </ul>
            {% endif %}

        {% else %}
            <div class="alert alert-warning">
                <p>No Hay Registto de Usuarios</p>
            </div>
        {% endif %}
    </div>
{% endblock %}

templates/layouts/master.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}DjangoBasico{% endblock %}</title>
    {% block styles %}
        <link rel="stylesheet" href="{% static 'libs/bootstrap/css/bootstrap-flaty.min.css' %}">
    {% endblock %}
    <style>
        body { padding-top: 70px; }
    </style>
</head>
<body>
    {% include "partials/header.html" %}
    <div class="container">
        {% block content %}{% endblock %}
    </div>
    {% block scripts %}
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    {% endblock %}
</body>
</html>

templates/partials/header.html
<header>
    <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navegacion">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/">DjangoBasico</a>
            </div>
            <div class="collapse navbar-collapse" id="navegacion">
                <ul class="nav navbar-nav" role="tablist">
                    <li class="active"><a href="#">Autor</a>
                    </li>
                    <li><a href="#">Item #2</a>
                    </li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Perfil<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="#">Opciones</a>
                            </li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    {% if messages %}
        <div class="container">
            <div class="row">
                <div class="col-xs-12">
                    {% for item in messages %}
                        <div class="alert alert-{{ item.tags }}" role="alert">
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                            <p>{{ item }}</p>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    {% endif %}
</header>

templates/tarjeta/form.html
{% extends "layouts/master.html" %}

{% block title %}
    Formulario de Tarjeta
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-sm-8 col-md-6 col-sm-offset-2 col-md-offset-3">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">Formulario de Tarjeta</h3>
                </div>
                <div class="panel-body">
                    <form method="POST" enctype="multipart/form-data" class="form">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <input type="submit" class="btn btn-block btn-primary" value="Guardar">
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/tarjeta/index.html
{% extends "layouts/master.html" %}

{% block title %}
    Tarjetas
{% endblock %}

{% block content %}
    {% if object_list %}
    <div class="row">
        {% for item in object_list %}
            <div class="col-xs-12 col-sm-6 col-md-4">
                <div class="panel panel-success">
                    <div class="panel-heading">
                        <h3 class="panel-title">{{ item.titulo }}</h3>
                    </div>
                    <div class="panel-body">
                        <img src="{{ item.imagen.url }}" class="img-responsive" alt="{{ item.titulo }}">
                    </div>
                    <div class="panel-footer">
                        <p>{{ item.autor }}</p>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
    {% else %}
        <div class="alert alert-warning" role="alert">
            <p>No Hay Tarjetas</p>
        </div>
    {% endif %}
{% endblock %}